<?php

return  [

"dishes" =>        [
[
    "name"=>"Chinese Chicken Salad",
    "price"=>"8.5",
    "image"=>"https://hips.hearstapps.com/hmg-prod/images/delish-190530-asian-chicken-mandarin-salad-259-landscape-pf-1559743395.png?crop=1xw:0.8435280189423836xh;center,top&resize=1200:*",
    "restaurant_id" => [7],
    "category_id" => 16,
    "ingredients"=> "pollame, salsa di soia, olio di sesamo, aglio, zenzero, aceto di vino, miele, sale, pepe nero",
    "description"=>"Insalata cinese di pollo",
    "available"=> true,
],

[
    "name"=>"Masterpiece Chicken & Dumplings Soup",
    "price"=>"7.5",
    "image"=>"https://thecozyapron.com/wp-content/uploads/2022/10/chicken-and-dumplings-soup_thecozyapron_1.jpg",
    "restaurant_id" => [7, 11],
    "category_id" => 6,
    "ingredients" => "ravioli, pollame, broccoli, coriandolo, olio di sesamo, semi di sesamo, asian stock powder",
    "description"=>"Gnocchi a base di pollo e verdure",
    "available"=> true,
],

[
    "name"=>"Wagyu Beef & Ginger Dumplings",
    "price"=>"12",
    "image"=>"https://imperialwagyubeef.com/wp-content/uploads/2020/11/Wagyu-Dumplings.jpg",
    "restaurant_id" => [3, 6],
    "category_id" => 15,                    
    "ingredients" => "pollame, cipolla, uova, zenzero, zucchero, olio di sesamo, semi di sesamo, soia, gochujang",
    "description" => "Gnocchi di carne",
    "available"=> true,
],

// continuare con inserimento piatti (ancora una decina tra burgers pizze altre cucine )
[
    "name"=>"Chicken Tacos",
    "price"=>"3.5",
    "image"=>"https://images.themodernproper.com/billowy-turkey/production/posts/2022/EasyChickenTacos_8.jpg?w=960&h=540&q=82&fm=jpg&fit=crop&dm=1664318931&s=c07ad178411eada8dc9c04cf8bb53489",
    "restaurant_id" => [11],
    "category_id"=>16,
    "ingredients" => "tortillas di mais, pollo, sale, paprika macinata, origano, timo, cipolla, aglio, pepe di cayenna, peperoncino, pepe nero",
    "description"=>"Tacos di pollo",
    "available"=> true,
],

[
    "name"=>"Popeye Burger",
    "price"=>"8.5",
    "image"=>"https://www.delfinosurgelati.it/wp-content/themes/yootheme/cache/3.2-veg-burger-e1648808280437-15dd11c5.jpeg",
    "restaurant_id" => [2, 3, 4, 8,11],
    "category_id"=>16,
    "ingredients" => "Hamburger di Spinaci, Patatine Fritte, Medaglione di Melanzane panate, Patate novelle al Forno, Pestato di Pomodoro Secco, Scamorza Affumicata, Cipolla Caramellata",
    "description"=>"Panino con hamburger di spinaci",
    "available"=> true,
],

[
    "name"=>"Chicken Burger",
    "price"=>"6.5",
    "image"=>"https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/10/1476374074_6347c4b4503328b1fdb3a57c9cb704a079fe66ed-1424529436.jpg?width=1280&height=720&quality=80",
    "restaurant_id" => [2, 3, 5, 1,11],
    "category_id"=>16,
    "ingredients" => "Sovraccoscia di Pollo Fritto, Pomodori, Bacon Croccante, Patatine Fritte, Fonduta di Parmigiano, Salsa Crispy Homemade Souce , Insalata",
    "description"=>"Panino con hamburger di pollo",
    "available"=> true,
],

[
    "name"=>"Raw No Beef",
    "price"=>"7.5",
    "image"=>"https://www.unileverfoodsolutions.at/dam/global-ufs/mcos/dach/calcmenu-recipes/ch-recipes/2021/tvb-bbq-global/healthy-gatsby-burger/healthy-gatsby-header.jpg",
    "restaurant_id" => [5, 11, 6, 7 ],
    "category_id"=>4,
    "ingredients" => "Raw No Beef(veg), Patate al Forno, Pestato di pomodoro secco, Patate novelle al Forno, Cipolla Rossa Grigliata",
    "description"=>"Panino vegano",
    "available"=> true,
],

[
    "name" => "Pizza La Ribelle",
    "price" => "7",
    "image" => "https://www.fattoamanopizza.com/wp-content/uploads/2023/07/Specials_FattoAMano-04-1-600x400.jpg",
    "restaurant_id" => [1, 2, 3, 4 ,8],
    "category_id"=>15,
    "ingredients" => "Mozzarella Fior di Latte, Bocconcino di Bufala, Basilico, Fonduta di Cheddar Artigianale , Olio Evo, Ragù di Ribs Homemade",
    "description" => "Pizza La Ribelle",
    "size" => "",
    "available"=> true,
],

[
    "name"=>"Pizza La Porcellona",
    "price"=>"7.5",
    "image"=>"https://media-cdn.tripadvisor.com/media/photo-s/0c/1a/cd/b7/pizza-porcellona.jpg",
    "restaurant_id" => [1, 2, 3, 4 ,8],
    "category_id"=>15,
    "ingredients" => "Mozzarella Fior di Latte, Pulled Pork, Crema di Cheddar, Cipolla Caramellata, Bacon, Chips di Patate Novelle",
    "description"=>"Pizza porcellona ",
    "available"=> true,
],

[
    "name"=>"Pizza Margherita",
    "price"=>"7.5",
    "image"=>"https://www.lagrandecucina.it/wp-content/uploads/2019/03/margherita-napoli-e1552848130892.jpg",
    "restaurant_id" =>  [1, 2, 3, 4 ,8],
    "category_id"=>15,
    "ingredients" => "Pomodoro, Mozzarella, Basilico",
    "description"=>"Classica pizza margherita",
    "available"=> true,
],

[
    "name"=>"Pizza La Cruda e Fusa",
    "price"=>"7",
    "image"=>"https://wips.plug.it/cips/buonissimo.org/cms/2011/12/pizza-al-prosciutto-cotto.jpg?w=712&a=c&h=406",
    "restaurant_id" => [1, 2, 3, 4 ,8],
    "category_id"=>16,
    "ingredients" => "Mozzarella Fior di Latte, Passata di pomodoro, Prosciutto Crudo, Fonduta di Parmigiano, Olio Evo, Sbriciolata di patate al forno",
    "description"=>"Pizza con prosciutto crudo",
    "available"=> true,
],

[
    "name"=>"Pizza La Crocchettona",
    "price"=>"6.5",
    "image"=>"https://static.alfonsino.cloud/uploads/products/2020/2FxEoAmh9yR5qCeuvpVQjcjE9cGkdx0KyDQ8elP3.jpg",
    "restaurant_id" => [1, 2, 3, 4 ,8],
    "category_id"=>16,
    "ingredients" => "Mozzarella Fior di Latte, Bacon, Olio Evo, Basilico, Crocchettone di Patate Menta e Pecorino, Fonduta al Pecorino Romano, Bocconcino di Bufala",
    "description"=>"Pizza con mozzarella e crocchette di patate",
    "available"=> true,
],

[
    "name"=>"Pizza La Vegetariana",
    "price"=>"7.5",
    "image"=>"https://www.guardini.com/images/guardinispa/ricette/full/pizza_set_2021_full.jpg",
    "restaurant_id" => [ 2, 3, 4 ,8 ,11],
    "category_id"=>7,
    "ingredients" => "Mozzarella Fior di Latte, Medaglione di Melanzane panate, Patate al Forno, Pestato di pomodoro secco",
    "description"=>"Pizza vegetariana",
    "available"=> true,
],

[
    "name"=>"Calzone Classico",
    "price"=>"6.5",
    "image"=>"https://i2.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2020/09/4460_Calzoni.jpg?resize=895%2C616&ssl=1",
    "restaurant_id" => [1, 2, 3, 4 ,8],
    "category_id"=>15,
    "ingredients" => "prociutto cotto, scamorza, parmigiano, ricotta di pecora",
    "description"=>"Calcone classico con pomodoro e mozzarella",
    "available"=> true,
],

[
    "name"=>"Insalata di mare",
    "price"=>"12",
    "image"=>"https://www.casapappagallo.it/storage/21432/Insalata-di-mare.jpg",
    "restaurant_id" => [5, 6, 13, 14, 15],
    "category_id"=>22,
    "ingredients" => "cozze, polpp, calamari, sedano, vongole, gamberi",
    "description"=>"Insalata di mare",
    "available"=> true,
],

[
    "name"=>"Gnocchi al ragù",
    "price"=>"10",
    "image"=>"https://lognocco.it/wp-content/uploads/2018/07/2-preparazione-ricetta-gnocchi-sugo.jpg",
    "restaurant_id" => [12, 9, 14, 15],
    "category_id"=>16,
    "ingredients" => "cipolle, patate, pomodori pelati, cipolle, carne macinata di manzo",
    "description"=>"Gnocchi di patate al ragù di casa",
    "available"=> true,
],

[
    "name"=>"Tagliatelle al ragù",
    "price"=>"10",
    "image"=>"https://d2sj0xby2hzqoy.cloudfront.net/kenwood_italy/attachments/data/000/010/485/medium/tagliatelle-al-ragu.jpg",
    "restaurant_id" => [12, 9, 14, 15],
    "category_id"=>15,
    "ingredients" => "tagliate all'uovo, sedano, manzo carne tritata, maiale carne tritata, carote",
    "description"=>"Tagliatelle al ragù della casa",
    "available"=> true,
],

[
    "name"=>"Spaghetti alla Carbonara",
    "price"=>"15",
    "image"=>"https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2021/03/Carbonara-ricetta-5328.jpg",
    "restaurant_id" => [12, 9, 14, 15],
    "category_id"=>16,
    "ingredients" => "spaghetti, tuorli, guanciale, pecorino romano, pepe nero",
    "description"=>"Spaghetti alla carbonara",
    "available"=> true,
],

[
    "name"=>"Spaghetti all'Amatriciana",
    "price"=>"16",
    "image"=>"https://cdn.cook.stbm.it/thumbnails/ricette/1/1198/hd750x421.jpg",
    "restaurant_id" => [12, 9, 14, 15],
    "category_id"=>16,
    "ingredients" => "spaghetti, guanciale, pecorino romano, pomodori pelati",
    "description"=>"Spaghetti all'Amatriciana",
    "available"=> true,
],


[
    "name"=>"Linguine Allo Scoglio",
    "price"=>"18",
    "image"=>"https://www.giallozafferano.it/images/ricette/182/18285/foto_hd/hd650x433_wm.jpg",
    "restaurant_id" => [5,6,11,13,14],
    "category_id"=>16,
    "ingredients" => "spaghetti, vongole, scampi, cozze, calamari",
    "description"=>"Linguine con vongole, scampi, cozze, calamari ",
    "available"=> true,
],

[
    "name"=>"Patate al forno",
    "price"=>"4",
    "image"=>"https://www.cucchiaio.it/content/cucchiaio/it/ricette/2015/04/patate-al-forno/_jcr_content/header-par/image-single.img.jpg/1581958003248.jpg",
    "restaurant_id" => [5,6,10,11,13,14,15],
    "category_id"=>16,
    "ingredients"=> "patate, aglio, rosmarino, pepe nero",
    "description"=>"Succose patate cotte al forno ",
    "available"=> true,
],

[
    "name"=>"Sagne Cacio e Pepe",
    "price"=>"9",
    "image"=>"https://2.bp.blogspot.com/-BtBkOYWU0yA/WoQljEGmPgI/AAAAAAAAVSI/xGqm83LWIp8vm0ZqhqHAutdBXjPMLBlmACLcBGAs/w1200-h630-p-k-no-nu/21034534_10212434137081765_4357364091545799219_n.jpg",
    "restaurant_id" => [9,12,6],
    "category_id"=>16,
    "ingredients"=> "fettine di guancialetto, pecorino romano, pepe nero",
    "description"=>"Pasta fatta in casa con cacio e pepe",
    "available"=> true,
],

[
    "name"=>"Tempura di gamberi",
    "price"=>"10",
    "image"=>"https://blog.giallozafferano.it/trasentieriefornelli/wp-content/uploads/2022/02/IMG_0029_1-960x640.jpg",
    "restaurant_id" => [7, 11],
    "category_id"=>7,
    "ingredients"=> "gamberi, farina di riso",
    "description"=>"Soffice tempura di gamberi",
    "available"=> true,
],

[
    "name"=>"Tempura di verdure",
    "price"=>"10",
    "image"=>"https://www.cucina-naturale.it/wp-content/uploads/2016/11/tempura-1-741x486.jpg",
    "restaurant_id" => [7, 14],
    "category_id"=>7,
    "ingredients"=> "verdure, farina di riso",
    "description"=>"Tempura mista di verdure pastellate",
    "available"=> true,
],

[
    "name"=>"Udon",
    "price"=>"16",
    "image"=>"https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/702bf478-0181-4a06-a273-061bf0020c5b/Derivates/7b779c29-79fd-4ec5-9517-2fc6cf97f624.jpg",
    "restaurant_id" => [7],
    "category_id"=>16,
    "ingredients"=> "udon, cipolla, uova, carote",
    "description"=>"Spaghetti bianche di grano con cipolla, uova, carote",
    "available"=> true,
],

[
    "name"=>"Noodles in brodo con tempura di pesce",
    "price"=>"14.50",
    "image"=>"https://www.ricetteinarmonia.it/wp-content/uploads/2020/10/Noodles-ai-frutti-di-mare-e-verdure-2-768x576.jpg",
    "restaurant_id" => [7],
    "category_id"=>15,
    "ingredients"=> "udon, gamberi, porro, uova",
    "description"=>"Noodles in brodo con tempura di pesce",
    "available"=> true,
],

[
    "name"=>"Katsudon",
    "price"=>"15",
    "image"=>"https://www.justonecookbook.com/wp-content/uploads/2020/05/Baked-Katsudon-9603-I-500x375.jpg",
    "restaurant_id" => [7],
    "category_id"=>16,
    "ingredients"=> "lonza di maiale, riso, uova",
    "description"=>"Gustosa cotoletta di maiale fritta",
    "available"=> true,
],

[
    "name"=>"Onion Rings",
    "price"=>"5",
    "image"=>"https://makeyourmeals.com/wp-content/uploads/2019/07/air-fryer-onion-rings-735x490.jpg",
    "restaurant_id" => [1, 3, 4, 5, 6, 8, 10],
    "category_id"=>16,
    "ingredients"=> "cipolle rosse, uova",
    "description"=>"Puzzolenti Anelli di cipolla fritta",
    "available"=> true,
],

// bibite

[
    "name"=>"Coca-Cola",
    "price"=>"2",
    "image"=>"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg/1200px-15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica al gusto cola",
    "available"=> true,
],

[
    "name"=>"Fanta",
    "price"=>"2",
    "image"=>"https://www.coca-cola.com/content/dam/onexp/it/it/home-images/brand-images/fanta/IT_fanta-original_750x750.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica al gusto arancia",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Coca-Cola Zero",
    "price"=>"2",
    "image"=>"https://www.coca-cola.com/content/dam/onexp/it/it/coca-cola/cczs/IT_cocacola-zero-zuccheri-_750x750.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica al gusto cola senza zuccheri",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Sprite",
    "price"=>"2",
    "image"=>"https://blacksmithpub.it/wp-content/uploads/sprite-vetro.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica gassata buona",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Pepsi",
    "price"=>"2",
    "image"=>"https://d5l1pnk7dv8vr.cloudfront.net/ARTICOLI/L_5212.png",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica al gusto cola ",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Acqua naturale",
    "price"=>"2",
    "image"=>"https://www.colizzivini.it/media/catalog/product/cache/a2269601488aaf6aadf9012f10675769/p/l/plose_nat_11.webp",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua",
    "description"=>"Acqua naturale",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Acqua frizzante",
    "price"=>"2",
    "image"=>"https://www.birimport.com/wp-content/uploads/2020/04/3728_acqua_lurisia_bolle_vap_75x12.png",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica.",
    "description"=>"Acqua frizzante ",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"The alla pesca",
    "price"=>"2",
    "image"=>"https://cdn.haitex.it/IT00194710604/img/i1v3_760128.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica a base si the al gusto pesca",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"The al limone",
    "price"=>"2",
    "image"=>"https://www.topbevande.it/images/thumbs/0091006_ferrero-estathe-limone-25cl-confezione-da-24-bottiglie-bottiglia-vetro_780.jpeg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica a base si the al gusto limone",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Chinotto",
    "price"=>"4.5",
    "image"=>"https://www.colizzivini.it/media/catalog/product/cache/a2269601488aaf6aadf9012f10675769/c/h/chinotto_san_pellegrino_1.webp",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, anidride carbonica, colorante E 150d, edulcoranti ciclammato di sodio, acesulfame K, aspartame, acidificante acido fosforico, aromi naturali (inclusa caffeina), correttore di acidità citrato trisodico.",
    "description"=>"Bevanda analcolica a base di chinotto",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Moretti",
    "price"=>"2.8",
    "image"=>"https://www.cantinadellabirra.it/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/o/moretti.png",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, cereali, lievito, luppolo.",
    "description"=>"La famosa birra del baffo italiana",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Heineken",
    "price"=>"2.8",
    "image"=>"https://www.birimport.com/wp-content/uploads/2020/04/330_birra_heineken_33x24.png",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, cereali, lievito, luppolo.",
    "description"=>"Famosa birra olandese",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Guinnes",
    "price"=>"3",
    "image"=>"https://www.gruppolazialebevande.it/wp-content/uploads/2016/04/0593_guinnessdraught.png",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, cereali, lievito, luppolo.",
    "description"=>"Birra stout di origine inglese",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Corona",
    "price"=>"3",
    "image"=>"https://www.bevisrl.com/components/com_jshopping/files/img_products/full_corona35_5cl.webp",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, cereali, lievito, luppolo.",
    "description"=>"Birra messicana leggere e dissetante",
    "size"=>"null",
    "available"=> true,
],

[
    "name"=>"Ichnusa",
    "price"=>"4.5",
    "image"=>"https://shop.taccolinidarfo.it/188-large_default/birra-ichnusa-033x24.jpg",
    "restaurant_id" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "category_id"=>1,
    "ingredients"=> "acqua, cereali, lievito, luppolo.",
    "description"=>"Birra di italiana, orgoglio dei sardi",
    "size"=>"null",
    "available"=> true,
],

]
];